#!/bin/bash

while read line; do
  if echo ${line} | grep "^#"; then
    echo ${line}
  fi

  y=`echo ${line} | cut -d ',' -f 2 | cut -d '.' -f 1`

  if [ $y -le 100 ]; then
    echo ${line}
  fi
done
